import { StyleSheet } from 'react-native';
import { theme } from '@/theme';

export const authStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: theme.colors.ink },
  content: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', padding: theme.spacing.lg },
  card: { width: '100%', maxWidth: 460, backgroundColor: theme.colors.inkRaised, borderRadius: theme.radii.lg, borderWidth: 1, borderColor: '#34322E', padding: theme.spacing.xl, ...theme.shadows.card },
  eyebrow: { color: theme.colors.copperSoft, fontFamily: theme.typography.body, fontSize: 12, fontWeight: '700', letterSpacing: 3, marginBottom: theme.spacing.xl },
  title: { color: theme.colors.ivory, fontFamily: theme.typography.display, fontSize: 38, lineHeight: 44, marginBottom: theme.spacing.sm },
  description: { color: theme.colors.stone, fontFamily: theme.typography.body, fontSize: 16, lineHeight: 24, marginBottom: theme.spacing.lg },
  label: { color: theme.colors.paper, fontFamily: theme.typography.body, fontSize: 13, fontWeight: '600', marginBottom: theme.spacing.xs },
  input: { minHeight: 54, borderWidth: 1, borderColor: '#4A4741', borderRadius: theme.radii.md, color: theme.colors.ivory, backgroundColor: '#121211', paddingHorizontal: theme.spacing.md, fontFamily: theme.typography.body, fontSize: 18, marginBottom: theme.spacing.md },
  otp: { textAlign: 'center', letterSpacing: 10, fontSize: 24 },
  button: { minHeight: theme.sizes.touch, borderRadius: theme.radii.pill, backgroundColor: theme.colors.copper, alignItems: 'center', justifyContent: 'center', paddingHorizontal: theme.spacing.lg },
  buttonMuted: { opacity: 0.48 },
  buttonText: { color: theme.colors.ink, fontFamily: theme.typography.body, fontWeight: '800', fontSize: 15 },
  secondary: { marginTop: theme.spacing.sm, backgroundColor: 'transparent', borderWidth: 1, borderColor: '#514E48' },
  secondaryText: { color: theme.colors.paper },
  helper: { color: theme.colors.stone, textAlign: 'center', fontSize: 12, lineHeight: 18, marginTop: theme.spacing.md },
  error: { color: theme.colors.error, fontSize: 13, marginBottom: theme.spacing.md },
  seal: { width: 54, height: 54, borderRadius: 27, alignItems: 'center', justifyContent: 'center', backgroundColor: '#292720', marginBottom: theme.spacing.lg },
  sealText: { color: theme.colors.copperSoft, fontSize: 24 },
  splashMark: { width: 76, height: 76, borderRadius: 38, borderWidth: 1, borderColor: theme.colors.copper, alignItems: 'center', justifyContent: 'center', marginBottom: theme.spacing.lg, backgroundColor: '#171613' },
  splashLetter: { color: theme.colors.ivory, fontFamily: theme.typography.display, fontSize: 38 },
  statusHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: theme.spacing.sm, marginBottom: theme.spacing.xl },
  statusHeaderCompact: { flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-start', gap: theme.spacing.xs },
  statusEyebrow: { flexShrink: 1, marginBottom: 0 },
  statusMeta: { flexShrink: 0, color: theme.colors.moss, fontFamily: theme.typography.body, fontSize: 10, fontWeight: '800', letterSpacing: 1.4 },
  statusActions: { width: '100%' },
  statusAction: { marginTop: 0 },
  statusActionSeparated: { marginTop: theme.spacing.sm },
  securityNote: { borderLeftWidth: 2, borderLeftColor: theme.colors.copper, paddingLeft: theme.spacing.md, marginBottom: theme.spacing.lg },
  securityNoteTitle: { color: theme.colors.paper, fontFamily: theme.typography.body, fontWeight: '700', marginBottom: theme.spacing.xxs },
  securityNoteText: { color: theme.colors.stone, fontFamily: theme.typography.body, fontSize: 12, lineHeight: 18 },
  inlineLoader: { marginTop: theme.spacing.md },
  profileFacts: { flexDirection: 'row', gap: theme.spacing.sm, marginBottom: theme.spacing.lg },
  fact: { flex: 1, minWidth: 0, borderTopWidth: 1, borderTopColor: '#3C3934', paddingTop: theme.spacing.sm },
  factLabel: { color: theme.colors.stone, fontFamily: theme.typography.body, fontSize: 10, fontWeight: '700', letterSpacing: 1.2, marginBottom: theme.spacing.xxs },
  factValue: { color: theme.colors.paper, fontFamily: theme.typography.body, fontSize: 13 },
  readonlyInput: { color: theme.colors.stone, backgroundColor: '#161512' },
  success: { color: theme.colors.moss, fontSize: 13, marginBottom: theme.spacing.md },
});
