import { fireEvent, render } from '@testing-library/react-native';
import { describe, expect, it, jest } from '@jest/globals';
import fs from 'node:fs';
import path from 'node:path';
import { visualAppAuthClient } from '@/app-auth/AppAuthClient';
import { ProfileScreen } from '@/screens/ProfileScreen';

describe('real access status and customer profile', () => {
  it('renders masked profile and account states without legacy data', async () => { const profile = await visualAppAuthClient.profile('token', 'device'); const screen = render(<ProfileScreen profile={profile} onSave={jest.fn()} onCancel={jest.fn()} onLogout={jest.fn()} />); expect(screen.getByText('+55 (***) *****-4321')).toBeTruthy(); expect(screen.getByLabelText('E-mail')).toHaveProp('value', 'a***@example.test'); expect(screen.queryByText(/CPF|endereço|cashback/i)).toBeNull(); });
  it('edits name and email and submits the optimistic version', async () => { const profile = await visualAppAuthClient.profile('token', 'device'); const onSave = jest.fn(); const screen = render(<ProfileScreen profile={profile} onSave={onSave} onCancel={jest.fn()} onLogout={jest.fn()} />); fireEvent.press(screen.getByLabelText('Editar perfil')); fireEvent.changeText(screen.getByLabelText('Nome completo'), 'Beatriz Cliente'); fireEvent.changeText(screen.getByLabelText('E-mail'), 'bia@example.test'); fireEvent.press(screen.getByLabelText('Salvar alterações')); expect(onSave).toHaveBeenCalledWith(expect.objectContaining({ version: profile.version, fullName: 'Beatriz Cliente', email: 'bia@example.test' })); });
  it('supports cancel, loading, success, error and logout feedback', async () => { const profile = await visualAppAuthClient.profile('token', 'device'); const onCancel = jest.fn(), onLogout = jest.fn(); const screen = render(<ProfileScreen profile={profile} loading error="Falha segura" success="Perfil salvo" onSave={jest.fn()} onCancel={onCancel} onLogout={onLogout} />); expect(screen.getByText('Falha segura')).toBeTruthy(); expect(screen.getByText('Perfil salvo')).toBeTruthy(); expect(screen.getByLabelText('Salvando perfil')).toBeTruthy(); fireEvent.press(screen.getByLabelText('Voltar ao status')); fireEvent.press(screen.getByLabelText('Sair da conta')); expect(onCancel).not.toHaveBeenCalled(); expect(onLogout).not.toHaveBeenCalled(); });
  it('visual fixture exposes save error and 409 conflict', async () => { const current = await visualAppAuthClient.profile('token', 'device'); await expect(visualAppAuthClient.updateProfile('token', 'device', { version: current.version, fullName: 'Conflito' })).rejects.toMatchObject({ status: 409 }); await expect(visualAppAuthClient.updateProfile('token', 'device', { version: current.version, fullName: 'Erro' })).rejects.toMatchObject({ status: 500 }); });
  it('refreshes status on app activation without polling', () => { const source = fs.readFileSync(path.join(process.cwd(), 'src', 'app', 'access-status.tsx'), 'utf8'); expect(source).toMatch(/AppState\.addEventListener/); expect(source).toMatch(/next === 'active'/); expect(source).not.toMatch(/setInterval|WebSocket/); });
  it('catalog and product routes always return to protected status', () => { const catalog = fs.readFileSync(path.join(process.cwd(), 'src', 'app', 'catalog.tsx'), 'utf8'); const product = fs.readFileSync(path.join(process.cwd(), 'src', 'app', 'product', '[slug].tsx'), 'utf8'); expect(catalog).toMatch(/access-status/); expect(product).toMatch(/access-status/); });
  it('profile actions expose visible focus and accessible labels', async () => { const profile = await visualAppAuthClient.profile('token', 'device'); const screen = render(<ProfileScreen profile={profile} onSave={jest.fn()} onCancel={jest.fn()} onLogout={jest.fn()} />); const edit = screen.getByLabelText('Editar perfil'); fireEvent(edit, 'focus', { currentTarget: { matches: (selector: string) => selector === ':focus-visible' } }); expect(edit.props.style).toBeTruthy(); expect(screen.getByLabelText('Nome completo')).toBeTruthy(); });
});
