"use strict";

const assert = require("node:assert/strict");
const test = require("node:test");
const sqlite3 = require("sqlite3");
const { applyAppCustomerAccessSchema } = require("../../app-access/persistence/appCustomerAccessSchema");
const { applyAppPhoneVerificationSchema } = require("../persistence/appPhoneVerificationSchema");
const { createAppPhoneOtpService, AppPhoneOtpError } = require("../appPhoneOtpService");
const { identifierLookupHash } = require("../../master/backfill/customerMasterControlledApply");

function memoryDb() {
  const connection = new sqlite3.Database(":memory:");
  return {
    run: (sql, params=[]) => new Promise((resolve,reject)=>connection.run(sql,params,function(error){error?reject(error):resolve({changes:this.changes,lastID:this.lastID});})),
    get: (sql, params=[]) => new Promise((resolve,reject)=>connection.get(sql,params,(error,row)=>error?reject(error):resolve(row))),
    all: (sql, params=[]) => new Promise((resolve,reject)=>connection.all(sql,params,(error,rows)=>error?reject(error):resolve(rows))),
    close: () => new Promise((resolve,reject)=>connection.close((error)=>error?reject(error):resolve()))
  };
}

async function fixture(options={}) {
  const db=memoryDb(); await db.run("PRAGMA foreign_keys=ON");
  await db.run("CREATE TABLE customer_master_records (id TEXT PRIMARY KEY,status TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,eligibility_status TEXT NOT NULL DEFAULT 'NOT_EVALUATED',updated_at TEXT NOT NULL,deleted_at TEXT)");
  await db.run("CREATE TABLE customer_master_identifiers (id TEXT PRIMARY KEY,master_id TEXT NOT NULL,source_link_id TEXT NOT NULL,identifier_type TEXT NOT NULL,lookup_hash TEXT NOT NULL,masked_value TEXT NOT NULL DEFAULT '',is_active INTEGER NOT NULL DEFAULT 1,FOREIGN KEY(master_id) REFERENCES customer_master_records(id))");
  await db.run("CREATE TABLE customer_identity_conflicts (id TEXT PRIMARY KEY,conflict_type TEXT NOT NULL,severity TEXT NOT NULL,status TEXT NOT NULL)");
  await db.run("CREATE TABLE customer_identity_conflict_participants (id TEXT PRIMARY KEY,conflict_id TEXT NOT NULL,participant_type TEXT NOT NULL,participant_id TEXT NOT NULL)");
  await db.run("CREATE TABLE customer_identity_cases (id TEXT PRIMARY KEY,blocking INTEGER NOT NULL DEFAULT 0)");
  await db.run("CREATE TABLE customer_identity_case_conflicts (case_id TEXT NOT NULL,conflict_id TEXT NOT NULL)");
  await db.run("CREATE TABLE contacts (id INTEGER PRIMARY KEY,name TEXT)");
  await db.run("CREATE TABLE crm_contacts (id INTEGER PRIMARY KEY,name TEXT)");
  await applyAppCustomerAccessSchema(db); await applyAppPhoneVerificationSchema(db);
  const clock={value:new Date("2026-08-01T12:00:00.000Z")}; const events=[];
  const whatsapp=options.whatsapp||{send:async()=>({success:true,status:"accepted",messageId:"secret-provider-id"})};
  const sms=options.sms||{available:true,send:async()=>({success:true,status:"pending",messageId:"sms-secret"}),verify:async({code})=>({success:code==="654321"})};
  const service=createAppPhoneOtpService({dbApi:db,pepper:"test-pepper-must-not-be-a-fallback",randomCode:()=>"123456",now:()=>new Date(clock.value),whatsapp,sms,recordAudit:(event)=>events.push(event),limits:{cooldown:1,fallbackDelay:1,...options.limits}});
  return {db,service,clock,events};
}

async function eligibleMaster(db, phone="5511987654321") {
  await db.run("INSERT INTO customer_master_records(id,status,updated_at) VALUES ('master-1','ACTIVE','2026-08-01T00:00:00.000Z')");
  await db.run("INSERT INTO customer_master_identifiers(id,master_id,source_link_id,identifier_type,lookup_hash,is_active) VALUES ('identifier-1','master-1','source-1','PHONE',?,1)",[identifierLookupHash("PHONE",phone)]);
}

test("schema OTP e reaplicacao sao expansivos e idempotentes",async()=>{const {db}=await fixture();assert.equal((await applyAppPhoneVerificationSchema(db)).ready,true);assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_phone_verifications")).total),0);await db.close();});
test("pepper obrigatorio impede inicializacao insegura",async()=>{const db=memoryDb();assert.throws(()=>createAppPhoneOtpService({dbApi:db,pepper:""}),/APP_OTP_PEPPER_REQUIRED/);await db.close();});
test("inicio envia seis digitos por WhatsApp sem expor codigo ou telefone",async()=>{const {db,service,events}=await fixture();const result=await service.start({phone:"(11) 98765-4321",ip:"1.2.3.4",deviceId:"device"});assert.equal(result.channel,"WHATSAPP");assert.doesNotMatch(JSON.stringify(result),/123456|98765/);const row=await db.get("SELECT * FROM app_phone_verifications");assert.equal(row.status,"SENT");assert.notEqual(row.otp_hash,"123456");assert.doesNotMatch(JSON.stringify(events),/123456|98765/);await db.close();});
test("novo desafio cancela o anterior e preserva somente um ativo",async()=>{const {db,service,clock}=await fixture();await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});clock.value=new Date(clock.value.getTime()+2000);await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_phone_verifications WHERE status='SENT'")).total),1);assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_phone_verifications WHERE status='CANCELLED'")).total),1);await db.close();});
test("OTP correto confirma telefone e aprova somente mestre unico elegivel",async()=>{const {db,service}=await fixture();await eligibleMaster(db);const challenge=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});const result=await service.verify({challengeId:challenge.challengeId,code:"123456"});assert.equal(result.accessStatus,"APPROVED");assert.ok(result.statusToken);assert.deepEqual(await service.status(result.statusToken),{phoneVerified:true,accessStatus:"APPROVED",accountStatus:"ACTIVE"});assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_access_decisions WHERE decision_type='AUTO_APPROVED_EXISTING_CUSTOMER'")).total),1);await db.close();});
test("telefone novo fica pendente e nunca ganha sessao definitiva",async()=>{const {db,service}=await fixture();const challenge=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});const result=await service.verify({challengeId:challenge.challengeId,code:"123456"});assert.equal(result.accessStatus,"PENDING_APPROVAL");assert.equal(Object.hasOwn(result,"sessionToken"),false);await db.close();});
test("candidato ambiguo permanece pendente e cria vinculos de conflito",async()=>{const {db,service}=await fixture();await eligibleMaster(db);await db.run("INSERT INTO customer_master_records(id,status,updated_at) VALUES ('master-2','ACTIVE','2026-08-01T00:00:00.000Z')");await db.run("INSERT INTO customer_master_identifiers(id,master_id,source_link_id,identifier_type,lookup_hash,is_active) VALUES ('identifier-2','master-2','source-2','PHONE',?,1)",[identifierLookupHash("PHONE","5511987654321")]);const c=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});assert.equal((await service.verify({challengeId:c.challengeId,code:"123456"})).accessStatus,"PENDING_APPROVAL");assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_customer_links WHERE link_status='CONFLICT'")).total),2);await db.close();});
test("codigo errado incrementa tentativas, bloqueia na quinta e nao vaza causa",async()=>{const {db,service}=await fixture();const c=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});for(let i=1;i<=5;i+=1){await assert.rejects(service.verify({challengeId:c.challengeId,code:"000000"}),(error)=>error instanceof AppPhoneOtpError&&(i<5?error.code==="OTP_INVALID_OR_EXPIRED":error.code==="OTP_LOCKED"));}assert.equal((await db.get("SELECT status FROM app_phone_verifications WHERE id=?",[c.challengeId])).status,"LOCKED");await db.close();});
test("desafio consumido nao pode ser reutilizado",async()=>{const {db,service}=await fixture();const c=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});await service.verify({challengeId:c.challengeId,code:"123456"});await assert.rejects(service.verify({challengeId:c.challengeId,code:"123456"}),/OTP_INVALID_OR_EXPIRED/);await db.close();});
test("expiracao invalida desafio",async()=>{const {db,service,clock}=await fixture();const c=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});clock.value=new Date(clock.value.getTime()+301000);await assert.rejects(service.verify({challengeId:c.challengeId,code:"123456"}),/OTP_INVALID_OR_EXPIRED/);assert.equal((await db.get("SELECT status FROM app_phone_verifications WHERE id=?",[c.challengeId])).status,"EXPIRED");await db.close();});
test("reenvio respeita cooldown e revoga desafio anterior",async()=>{const {db,service,clock}=await fixture();const c=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});await assert.rejects(service.resend({challengeId:c.challengeId,ip:"ip",deviceId:"d"}),/OTP_COOLDOWN/);clock.value=new Date(clock.value.getTime()+2000);const next=await service.resend({challengeId:c.challengeId,ip:"ip",deviceId:"d"});assert.notEqual(next.challengeId,c.challengeId);await db.close();});
test("SMS so aparece apos atraso ou falha e usa Verify para conferir",async()=>{const {db,service,clock}=await fixture();const c=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});await assert.rejects(service.useSms({challengeId:c.challengeId,ip:"ip",deviceId:"d"}),/SMS_NOT_AVAILABLE_YET/);clock.value=new Date(clock.value.getTime()+2000);const sms=await service.useSms({challengeId:c.challengeId,ip:"ip",deviceId:"d"});assert.equal(sms.channel,"SMS");assert.equal((await service.verify({challengeId:sms.challengeId,code:"654321"})).accessStatus,"PENDING_APPROVAL");await db.close();});
test("indisponibilidade SMS nao derruba WhatsApp",async()=>{const {db,service,clock}=await fixture({sms:{available:false}});const c=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});assert.equal(c.channel,"WHATSAPP");clock.value=new Date(clock.value.getTime()+2000);await assert.rejects(service.useSms({challengeId:c.challengeId}),/SMS_UNAVAILABLE/);await db.close();});
test("limite por telefone bloqueia abuso com HTTP logico 429",async()=>{const {db,service,clock}=await fixture({limits:{perPhone:2}});for(let i=0;i<2;i+=1){await service.start({phone:"11987654321",ip:`ip${i}`,deviceId:`d${i}`});clock.value=new Date(clock.value.getTime()+2000);}await assert.rejects(service.start({phone:"11987654321",ip:"ip3",deviceId:"d3"}),(error)=>error.code==="OTP_RATE_LIMITED"&&error.status===429);await db.close();});
test("token de status adulterado ou expirado e recusado",async()=>{const {db,service}=await fixture();await assert.rejects(service.status("invalid.token"),/STATUS_TOKEN_INVALID/);await db.close();});
test("telefone invalido e finalidade nao permitida sao recusados sem enumeracao",async()=>{const {db,service}=await fixture();await assert.rejects(service.start({phone:"123",ip:"ip",deviceId:"d"}),/OTP_INVALID_REQUEST/);await assert.rejects(service.start({phone:"11987654321",purpose:"CPF_LOGIN",ip:"ip",deviceId:"d"}),/OTP_INVALID_REQUEST/);await db.close();});
test("inicio tem o mesmo contrato para conta existente e inexistente",async()=>{const {db,service,clock}=await fixture();const first=await service.start({phone:"11987654321",ip:"ip1",deviceId:"d1"});await db.run("INSERT INTO app_customer_accounts(id,phone_lookup_hash,phone_masked,email_lookup_hash,email_masked,account_status,access_status,version,created_at,updated_at) VALUES ('x',?,'***','','','ACTIVE','PENDING_PHONE_VERIFICATION',1,?,?)",[require('node:crypto').createHash('sha256').update('5521987654321').digest('hex'),clock.value.toISOString(),clock.value.toISOString()]);clock.value=new Date(clock.value.getTime()+2000);const second=await service.start({phone:"21987654321",ip:"ip2",deviceId:"d2"});assert.deepEqual(Object.keys(first).sort(),Object.keys(second).sort());await db.close();});
test("rate limit independente por IP e dispositivo",async()=>{for(const dimension of ['ip','device']){const {db,service,clock}=await fixture({limits:{perIp:2,perDevice:2,perPhone:20}});for(let i=0;i<2;i+=1){await service.start({phone:`1198765432${i}`,ip:dimension==='ip'?'shared':`ip${i}`,deviceId:dimension==='device'?'shared':`d${i}`});clock.value=new Date(clock.value.getTime()+2000);}await assert.rejects(service.start({phone:"11987654329",ip:dimension==='ip'?'shared':'ip9',deviceId:dimension==='device'?'shared':'d9'}),/OTP_RATE_LIMITED/);await db.close();}});
test("PHONE_SHARED e conflito CPF impedem autoaprovacao",async()=>{for(const type of ['PHONE_SHARED','CPF_DUPLICATE']){const {db,service}=await fixture();await eligibleMaster(db);await db.run("INSERT INTO customer_identity_conflicts(id,conflict_type,severity,status) VALUES ('conflict',?,'BLOCKING','OPEN')",[type]);await db.run("INSERT INTO customer_identity_conflict_participants(id,conflict_id,participant_type,participant_id) VALUES ('p','conflict','MASTER','master-1')");const challenge=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});assert.equal((await service.verify({challengeId:challenge.challengeId,code:"123456"})).accessStatus,"PENDING_APPROVAL");await db.close();}});
test("fluxo OTP nao escreve em contacts ou crm_contacts",async()=>{const {db,service}=await fixture();await db.run("INSERT INTO contacts(id,name) VALUES (1,'legado')");await db.run("INSERT INTO crm_contacts(id,name) VALUES (1,'crm')");const challenge=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});await service.verify({challengeId:challenge.challengeId,code:"123456"});assert.deepEqual(await db.get("SELECT * FROM contacts"),{id:1,name:'legado'});assert.deepEqual(await db.get("SELECT * FROM crm_contacts"),{id:1,name:'crm'});await db.close();});
test("auditoria cobre ciclo sem OTP ou PII integral",async()=>{const {db,service,events}=await fixture();const challenge=await service.start({phone:"11987654321",ip:"ip",deviceId:"d"});await service.verify({challengeId:challenge.challengeId,code:"123456"});const actions=events.map((event)=>event.action);for(const expected of ['OTP_CHALLENGE_CREATED','OTP_SENT_WHATSAPP','OTP_VERIFIED','APP_ACCOUNT_CREATED','APP_ACCESS_REQUEST_CREATED','APP_AUTO_APPROVAL_EVALUATED'])assert.ok(actions.includes(expected));assert.doesNotMatch(JSON.stringify(events),/123456|11987654321/);await db.close();});
