"use strict";

const assert=require("node:assert/strict"); const test=require("node:test"); const sqlite3=require("sqlite3");
const {applyAppCustomerAccessSchema}=require("../../app-access/persistence/appCustomerAccessSchema");
const {createAppCustomerAccessService}=require("../../app-access/appCustomerAccessService");
const {applyAppSessionSchema,getAppSessionSchemaStatus}=require("../persistence/appSessionSchema");
const {AppSessionError,createAppSessionService}=require("../appSessionService");
const {createRequireAppSession}=require("../appSessionRoutes");

function memoryDb(){const connection=new sqlite3.Database(":memory:");return{run:(sql,p=[])=>new Promise((resolve,reject)=>connection.run(sql,p,function(error){error?reject(error):resolve({changes:this.changes,lastID:this.lastID});})),get:(sql,p=[])=>new Promise((resolve,reject)=>connection.get(sql,p,(error,row)=>error?reject(error):resolve(row))),all:(sql,p=[])=>new Promise((resolve,reject)=>connection.all(sql,p,(error,rows)=>error?reject(error):resolve(rows))),close:()=>new Promise((resolve,reject)=>connection.close((error)=>error?reject(error):resolve()))};}
async function fixture(config={}){const db=memoryDb();await db.run("PRAGMA foreign_keys=ON");await db.run("CREATE TABLE customer_master_records(id TEXT PRIMARY KEY,status TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,eligibility_status TEXT NOT NULL DEFAULT 'NOT_EVALUATED',updated_at TEXT NOT NULL,deleted_at TEXT)");await db.run("CREATE TABLE customer_identity_conflicts(id TEXT PRIMARY KEY,conflict_type TEXT,severity TEXT,status TEXT)");await db.run("CREATE TABLE customer_identity_conflict_participants(id TEXT PRIMARY KEY,conflict_id TEXT,participant_type TEXT,participant_id TEXT)");await db.run("CREATE TABLE customer_identity_cases(id TEXT PRIMARY KEY,blocking INTEGER)");await db.run("CREATE TABLE customer_identity_case_conflicts(case_id TEXT,conflict_id TEXT)");await applyAppCustomerAccessSchema(db);await applyAppSessionSchema(db);const clock={value:new Date("2026-08-01T12:00:00.000Z")},events=[];let tokenIndex=0;const service=createAppSessionService({dbApi:db,jwtSecret:"jwt-secret-for-tests-only-at-least-32-characters",pepper:"session-pepper-for-tests-at-least-32-characters",now:()=>new Date(clock.value),randomToken:()=>`refresh-test-token-${++tokenIndex}-${"x".repeat(40)}`,recordAudit:(event)=>events.push(event),limits:config.limits});return{db,service,clock,events};}
async function seed(db,{id="account-1",accountStatus="ACTIVE",accessStatus="APPROVED",tokenVersion=1,master=true}={}){const now="2026-08-01T11:00:00.000Z";await db.run(`INSERT INTO app_customer_accounts(id,phone_lookup_hash,phone_masked,phone_verified_at,email_lookup_hash,email_masked,account_status,access_status,version,created_at,updated_at,token_version) VALUES (?,?,?,?,'','','${accountStatus}','${accessStatus}',1,?,?,?)`,[id,`hash-${id}`,"***-4321",now,now,now,tokenVersion]);await db.run(`INSERT INTO app_access_requests(id,account_id,request_type,status,submitted_profile_json,submitted_at,version,created_at,updated_at) VALUES (?,?, 'EXISTING_CUSTOMER_LINK','${accessStatus==='APPROVED'?'APPROVED':'PENDING_APPROVAL'}','{}',?,1,?,?)`,[`request-${id}`,id,now,now,now]);if(master){await db.run("INSERT OR IGNORE INTO customer_master_records(id,status,updated_at) VALUES ('master-1','ACTIVE',?)",[now]);await db.run("INSERT INTO app_customer_links(id,account_id,master_id,link_status,link_type,confidence,created_at,updated_at) VALUES (?,?,?,'ACTIVE','PHONE_IDENTIFIER',100,?,?)",[`link-${id}`,id,"master-1",now,now]);}}
const device=(suffix="1")=>({accountId:"account-1",deviceId:`device-${suffix}`,deviceName:`iPhone ${suffix}`,platform:"IOS",appVersion:"1.0.0",ip:`10.0.0.${suffix}`,userAgent:"AEROSTORE App"});

test("schema adiciona token_version e app_sessions de forma idempotente",async()=>{const{db}=await fixture();const second=await applyAppSessionSchema(db);assert.equal(second.after.ready,true);assert.equal((await getAppSessionSchemaStatus(db)).sessions,0);await db.close();});
test("segredos obrigatorios impedem fallback inseguro",async()=>{const db=memoryDb();assert.throws(()=>createAppSessionService({dbApi:db,jwtSecret:"",pepper:"pepper-long-enough-for-isolated-test"}),/APP_JWT_SECRET_REQUIRED/);assert.throws(()=>createAppSessionService({dbApi:db,jwtSecret:"jwt-secret-long-enough-for-isolated-test",pepper:""}),/APP_SESSION_PEPPER_REQUIRED/);await db.close();});
test("cria sessao persistindo somente hash e JWT allow-list por 15 minutos",async()=>{const{db,service}=await fixture();await seed(db);const tokens=await service.createSession(device());const row=await db.get("SELECT * FROM app_sessions");assert.equal(row.status,"ACTIVE");assert.notEqual(row.refresh_hash,tokens.refreshToken);assert.doesNotMatch(JSON.stringify(row),/refresh-test-token/);const payload=service.parseAccessToken(tokens.accessToken);assert.deepEqual(Object.keys(payload).sort(),["access_status","account_id","exp","expires_at","iat","issued_at","master_id","session_id","token_version"].sort());assert.equal(payload.expires_at-payload.issued_at,900);assert.doesNotMatch(JSON.stringify(payload),/phone|email|cpf|hash|address/i);await db.close();});
test("metadados do dispositivo mascaram telefone e email",async()=>{const{db,service}=await fixture();await seed(db);await service.createSession({...device(),deviceName:"iPhone 11987654321 cliente@example.test"});const name=(await db.get("SELECT device_name FROM app_sessions")).device_name;assert.doesNotMatch(name,/11987654321|cliente@example\.test/);assert.match(name,/\[phone\]|\[email\]/);await db.close();});
test("rotacao invalida refresh anterior e produz nova geracao",async()=>{const{db,service}=await fixture();await seed(db);const first=await service.createSession(device());const next=await service.refresh({refreshToken:first.refreshToken,...device()});assert.notEqual(next.refreshToken,first.refreshToken);assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_sessions WHERE status='ACTIVE'")).total),1);assert.equal((await db.get("SELECT revoke_reason FROM app_sessions WHERE parent_session_id IS NULL")).revoke_reason,"ROTATED");await db.close();});
test("reutilizacao revoga a familia inteira e incrementa token_version",async()=>{const{db,service}=await fixture();await seed(db);const first=await service.createSession(device());await service.refresh({refreshToken:first.refreshToken,...device()});await assert.rejects(service.refresh({refreshToken:first.refreshToken,...device()}),/REFRESH_TOKEN_REUSED/);assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_sessions WHERE status='ACTIVE'")).total),0);assert.equal((await db.get("SELECT token_version FROM app_customer_accounts WHERE id='account-1'")).token_version,2);await db.close();});
test("logout revoga somente dispositivo atual",async()=>{const{db,service}=await fixture();await seed(db);const one=await service.createSession(device("1"));await service.createSession(device("2"));const context=await service.authenticateAccess(one.accessToken,{allowPending:true});await service.logout(context.session.id);assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_sessions WHERE status='ACTIVE'")).total),1);await db.close();});
test("logout repetido e idempotente",async()=>{const{db,service,events}=await fixture();await seed(db);const one=await service.createSession(device());const context=await service.authenticateAccess(one.accessToken,{allowPending:true});await service.logout(context.session.id);await service.logout(context.session.id);assert.equal(events.filter((event)=>event.action==="SESSION_REVOKED").length,1);await db.close();});
test("logout global revoga todos e invalida versao",async()=>{const{db,service}=await fixture();await seed(db);const one=await service.createSession(device("1"));await service.createSession(device("2"));const context=await service.authenticateAccess(one.accessToken,{allowPending:true});await service.logoutAll(context.account.id);assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_sessions WHERE status='ACTIVE'")).total),0);await assert.rejects(service.authenticateAccess(one.accessToken,{allowPending:true}),/SESSION_REVOKED/);assert.equal((await db.get("SELECT token_version FROM app_customer_accounts")).token_version,2);await db.close();});
test("access expirado e assinatura adulterada retornam 401",async()=>{const{db,service,clock}=await fixture();await seed(db);const tokens=await service.createSession(device());clock.value=new Date(clock.value.getTime()+901000);await assert.rejects(service.authenticateAccess(tokens.accessToken),/ACCESS_TOKEN_EXPIRED/);await assert.rejects(service.authenticateAccess(`${tokens.accessToken.slice(0,-1)}x`),/ACCESS_TOKEN_INVALID/);await db.close();});
test("refresh expirado marca sessao EXPIRED",async()=>{const{db,service,clock}=await fixture({limits:{refreshSeconds:10}});await seed(db);const tokens=await service.createSession(device());clock.value=new Date(clock.value.getTime()+11000);await assert.rejects(service.refresh({refreshToken:tokens.refreshToken,...device()}),/REFRESH_TOKEN_EXPIRED/);assert.equal((await db.get("SELECT status FROM app_sessions")).status,"EXPIRED");await db.close();});
for(const [field,value,expected] of [["account_status","BLOCKED","BLOCKED"],["account_status","SUSPENDED","SUSPENDED"],["access_status","REJECTED","REJECTED"]])test(`${value} responde 403 no middleware`,async()=>{const{db,service}=await fixture();await seed(db,{accountStatus:"ACTIVE",accessStatus:"APPROVED"});const tokens=await service.createSession(device());await db.run(`UPDATE app_customer_accounts SET ${field}=? WHERE id='account-1'`,[value]);await assert.rejects(service.authenticateAccess(tokens.accessToken),(error)=>error instanceof AppSessionError&&error.status===403&&error.accessStatus===expected);await db.close();});
test("token_version alterado invalida JWT e sessao",async()=>{const{db,service}=await fixture();await seed(db);const tokens=await service.createSession(device());await db.run("UPDATE app_customer_accounts SET token_version=token_version+1");await assert.rejects(service.authenticateAccess(tokens.accessToken),/TOKEN_VERSION_INVALID/);await db.close();});
test("bloqueio administrativo incrementa token_version",async()=>{const{db}=await fixture();await seed(db);await createAppCustomerAccessService(db).decide("account-1","BLOCK",{id:"admin-1",role:"admin"},{expectedVersion:1,reason:"Comprometimento confirmado"});assert.equal((await db.get("SELECT token_version FROM app_customer_accounts WHERE id='account-1'")).token_version,2);await db.close();});
test("multiplos dispositivos coexistem e mesmo dispositivo substitui sessao anterior",async()=>{const{db,service}=await fixture();await seed(db);await service.createSession(device("1"));await service.createSession(device("2"));assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_sessions WHERE status='ACTIVE'")).total),2);await service.createSession(device("1"));assert.equal(Number((await db.get("SELECT COUNT(*) total FROM app_sessions WHERE status='ACTIVE'")).total),2);await db.close();});
test("limite de sessoes e de refresh produz 429",async()=>{const{db,service}=await fixture({limits:{maxActiveSessions:1,maxRefreshPerHour:1}});await seed(db);const first=await service.createSession(device("1"));await assert.rejects(service.createSession(device("2")),(error)=>error.status===429);await assert.rejects(service.refresh({refreshToken:first.refreshToken,...device("1")}),(error)=>error.status===429);await db.close();});
test("middleware consulta banco e chama next somente para sessao valida",async()=>{const{db,service}=await fixture();await seed(db);const tokens=await service.createSession(device());let next=false,statusCode=0;const req={get:(name)=>name==="authorization"?`Bearer ${tokens.accessToken}`:"",body:{}};const res={status(code){statusCode=code;return this;},json(){return this;}};await createRequireAppSession(service)(req,res,()=>{next=true;});assert.equal(next,true);await service.logout(req.appSession.session.id);next=false;await createRequireAppSession(service)(req,res,()=>{next=true;});assert.equal(next,false);assert.equal(statusCode,401);await db.close();});
test("auditoria nao contem tokens, telefone ou PII",async()=>{const{db,service,events}=await fixture();await seed(db);const first=await service.createSession(device());await service.refresh({refreshToken:first.refreshToken,...device()});const serialized=JSON.stringify(events);assert.doesNotMatch(serialized,/refresh-test-token|Bearer|phone|cpf|email/i);assert.ok(events.some((event)=>event.action==="SESSION_CREATED"));assert.ok(events.some((event)=>event.action==="SESSION_REFRESHED"));assert.ok(events.some((event)=>event.action==="LOGIN_COMPLETED"));await db.close();});
test("duas renovacoes concorrentes nunca deixam dois refresh ativos",async()=>{const{db,service}=await fixture();await seed(db);const first=await service.createSession(device());const results=await Promise.allSettled([service.refresh({refreshToken:first.refreshToken,...device()}),service.refresh({refreshToken:first.refreshToken,...device()})]);assert.ok(results.some((result)=>result.status==="rejected"));assert.ok(Number((await db.get("SELECT COUNT(*) total FROM app_sessions WHERE status='ACTIVE'")).total)<=1);await db.close();});
